### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by markudevelop** [af/apollo-local-query#1]
````
W20161217-12:43:23.389(1)? (STDERR) const createLocalInterface = (graphql, schema, {rootValue = null, context = null} = {}) => {
W20161217-12:43:23.390(1)? (STDERR)                                                ^
W20161217-12:43:23.390(1)? (STDERR)           
W20161217-12:43:23.390(1)? (STDERR) ReferenceError: Invalid left-hand side in assignment
````
just wanted to let you know

**Comment by af** [comment]
Thanks for the report, which Node version are you running? The current
implementation requires 6+, although the module is so simple that I should
support older versions as well

On Dec 17, 2016 3:44 AM, "Mark Uretsky" <notifications@github.com> wrote:

W20161217-12:43:23.389(1)? (STDERR) const createLocalInterface =
(graphql, schema, {rootValue = null, context = null} = {}) => {
W20161217-12:43:23.390(1)? (STDERR)
            ^
W20161217-12:43:23.390(1)? (STDERR)
W20161217-12:43:23.390(1)? (STDERR) ReferenceError: Invalid left-hand
side in assignment

just wanted to let you know

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/af/apollo-local-query/issues/1>, or mute the thread

**Comment by af** [comment]
Keeping the v6+ requirement for now, but if this is an issue for a lot of people we can revisit this. Now the package.json and Readme reflect this, thanks for the heads up!
